name: Deploy Service A

on:
  push:
    branches:
      - main
    paths:
      - 'lib/service-a-stack.ts'
      - 'assets/lambda-functions/service_a_handler.js'
      - 'lib/models/service-a-models.ts'
      - '.github/workflows/deploy-service-a.yml'
      - '.github/workflows/deploy-stack.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-service-a:
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack-name: ServiceAStack
      stack-prefix: service-a
      environment: prod
    secrets:
      AWS_ROLE_ARN: arn:aws:iam::834197531540:role/testgithub
      AWS_REGION: us-west-2
  deploy-service-b:
    needs: deploy-service-a
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack-name: ServiceBStack
      stack-prefix: service-b
      environment: prod
    secrets:
      AWS_ROLE_ARN: arn:aws:iam::834197531540:role/testgithub
      AWS_REGION: us-west-2
